version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: f1schedule
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
